INSERT INTO pisces_pisces_dp ( `product_id`, `dp_id`, `group`, `schema`, `gmt_create` ) VALUES
	( '0jmuzs0x', 1, 5, '{"actions":[{"actionDisplay":"震动传感器_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==","vibration"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"震动传感器_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( 'wpmo3ja3', 1, 5, '{"actions":[{"actionDisplay":"CO报警器_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==","1"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"CO报警器_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( 'immt7yly', 1, 5, '{"actions":[{"actionDisplay":"CO报警器_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==","1"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"CO报警器_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( 'tob46aoq', 1, 5, '{"actions":[{"actionDisplay":"烟雾报警器_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==","1"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"烟雾报警器_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( '18pkine6', 1, 5, '{"actions":[{"actionDisplay":"燃气报警器_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==","1"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"燃气报警器_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( '4z5hspgj', 1, 5, '{"actions":[{"actionDisplay":"燃气报警器_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==","1"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"燃气报警器_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( 'lgpxxutv', 1, 5, '{"actions":[{"actionDisplay":"烟雾报警器_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==","1"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"烟雾报警器_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( 'mrwlggy8', 1, 5, '{"actions":[{"actionDisplay":"海曼人体红外探测器_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==","pir"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"海曼人体红外探测器_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( 'ho6i0zk9', 1, 5, '{"actions":[{"actionDisplay":"海曼门磁_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==",true]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"海曼门磁_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( 'ezhgerjm', 1, 5, '{"actions":[{"actionDisplay":"海曼水浸传感器_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp1","==","1"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"海曼水浸传感器_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),
	( 'fod6ibas', 23, 5, '{"actions":[{"actionDisplay":"紧急按钮_触发发送kafka消息","actionExecutor":"linkageTriggerNotice","actionStrategy":"repeat","entityId":"linkage_home_security_condition_trigger","entityName":"触发传感器topic"}],"boundForPanel":false,"conditions":[{"condType":1,"entitySubIds":"1","entityType":1,"expr":[["$dp23","==","true"]],"extraInfo":{}}],"localLinkage":false,"logicRule":false,"matchType":2,"name":"紧急按钮_联动摄像头","newLocalScene":false,"ruleType":3,"scenarioRule":true,"stickyOnTop":false}', unix_timestamp(now())*1000 ),

