// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.proto;

public final class StudentModule {
    private StudentModule() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface ProtoBufStudentOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string name = 1;
        boolean hasName();

        String getName();

        // required int32 age = 2;
        boolean hasAge();

        int getAge();

        // required float grade = 3;
        boolean hasGrade();

        float getGrade();
    }

    public static final class ProtoBufStudent extends
            com.google.protobuf.GeneratedMessage
            implements ProtoBufStudentOrBuilder {
        // Use ProtoBufStudent.newBuilder() to construct.
        private ProtoBufStudent(Builder builder) {
            super(builder);
        }

        private ProtoBufStudent(boolean noInit) {
        }

        private static final ProtoBufStudent defaultInstance;

        public static ProtoBufStudent getDefaultInstance() {
            return defaultInstance;
        }

        public ProtoBufStudent getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return StudentModule.internal_static_ProtoBufStudent_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return StudentModule.internal_static_ProtoBufStudent_fieldAccessorTable;
        }

        private int bitField0_;
        // required string name = 1;
        public static final int NAME_FIELD_NUMBER = 1;
        private Object name_;

        public boolean hasName() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getName() {
            Object ref = name_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    name_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getNameBytes() {
            Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required int32 age = 2;
        public static final int AGE_FIELD_NUMBER = 2;
        private int age_;

        public boolean hasAge() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public int getAge() {
            return age_;
        }

        // required float grade = 3;
        public static final int GRADE_FIELD_NUMBER = 3;
        private float grade_;

        public boolean hasGrade() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        public float getGrade() {
            return grade_;
        }

        private void initFields() {
            name_ = "";
            age_ = 0;
            grade_ = 0F;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAge()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasGrade()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, age_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeFloat(3, grade_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getNameBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, age_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeFloatSize(3, grade_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static StudentModule.ProtoBufStudent parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static StudentModule.ProtoBufStudent parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static StudentModule.ProtoBufStudent parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static StudentModule.ProtoBufStudent parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static StudentModule.ProtoBufStudent parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static StudentModule.ProtoBufStudent parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static StudentModule.ProtoBufStudent parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static StudentModule.ProtoBufStudent parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static StudentModule.ProtoBufStudent parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static StudentModule.ProtoBufStudent parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(StudentModule.ProtoBufStudent prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements StudentModule.ProtoBufStudentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return StudentModule.internal_static_ProtoBufStudent_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return StudentModule.internal_static_ProtoBufStudent_fieldAccessorTable;
            }

            // Construct using StudentModule.ProtoBufStudent.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                age_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                grade_ = 0F;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return StudentModule.ProtoBufStudent.getDescriptor();
            }

            public StudentModule.ProtoBufStudent getDefaultInstanceForType() {
                return StudentModule.ProtoBufStudent.getDefaultInstance();
            }

            public StudentModule.ProtoBufStudent build() {
                StudentModule.ProtoBufStudent result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private StudentModule.ProtoBufStudent buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                StudentModule.ProtoBufStudent result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public StudentModule.ProtoBufStudent buildPartial() {
                StudentModule.ProtoBufStudent result = new StudentModule.ProtoBufStudent(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.name_ = name_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.age_ = age_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.grade_ = grade_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof StudentModule.ProtoBufStudent) {
                    return mergeFrom((StudentModule.ProtoBufStudent) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(StudentModule.ProtoBufStudent other) {
                if (other == StudentModule.ProtoBufStudent.getDefaultInstance()) return this;
                if (other.hasName()) {
                    setName(other.getName());
                }
                if (other.hasAge()) {
                    setAge(other.getAge());
                }
                if (other.hasGrade()) {
                    setGrade(other.getGrade());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasName()) {

                    return false;
                }
                if (!hasAge()) {

                    return false;
                }
                if (!hasGrade()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            name_ = input.readBytes();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            age_ = input.readInt32();
                            break;
                        }
                        case 29: {
                            bitField0_ |= 0x00000004;
                            grade_ = input.readFloat();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string name = 1;
            private Object name_ = "";

            public boolean hasName() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getName() {
                Object ref = name_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setName(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
                return this;
            }

            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            void setName(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                name_ = value;
                onChanged();
            }

            // required int32 age = 2;
            private int age_;

            public boolean hasAge() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public int getAge() {
                return age_;
            }

            public Builder setAge(int value) {
                bitField0_ |= 0x00000002;
                age_ = value;
                onChanged();
                return this;
            }

            public Builder clearAge() {
                bitField0_ = (bitField0_ & ~0x00000002);
                age_ = 0;
                onChanged();
                return this;
            }

            // required float grade = 3;
            private float grade_;

            public boolean hasGrade() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            public float getGrade() {
                return grade_;
            }

            public Builder setGrade(float value) {
                bitField0_ |= 0x00000004;
                grade_ = value;
                onChanged();
                return this;
            }

            public Builder clearGrade() {
                bitField0_ = (bitField0_ & ~0x00000004);
                grade_ = 0F;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:ProtoBufStudent)
        }

        static {
            defaultInstance = new ProtoBufStudent(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:ProtoBufStudent)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_ProtoBufStudent_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_ProtoBufStudent_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\rstudent.proto\";\n\017ProtoBufStudent\022\014\n\004na" +
                        "me\030\001 \002(\t\022\013\n\003age\030\002 \002(\005\022\r\n\005grade\030\003 \002(\002B\027\n\006" +
                        "com.zlB\rStudentModule"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_ProtoBufStudent_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_ProtoBufStudent_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_ProtoBufStudent_descriptor,
                                new String[]{"Name", "Age", "Grade",},
                                StudentModule.ProtoBufStudent.class,
                                StudentModule.ProtoBufStudent.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
