
package com.webservice.server;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FuncInterfaceImplService", targetNamespace = "http://interfaces.webservice.com/", wsdlLocation = "http://localhost:8888/func/1?wsdl")
public class FuncInterfaceImplService
    extends Service
{

    private final static URL FUNCINTERFACEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FUNCINTERFACEIMPLSERVICE_EXCEPTION;
    private final static QName FUNCINTERFACEIMPLSERVICE_QNAME = new QName("http://interfaces.webservice.com/", "FuncInterfaceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/func/1?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUNCINTERFACEIMPLSERVICE_WSDL_LOCATION = url;
        FUNCINTERFACEIMPLSERVICE_EXCEPTION = e;
    }

    public FuncInterfaceImplService() {
        super(__getWsdlLocation(), FUNCINTERFACEIMPLSERVICE_QNAME);
    }

    public FuncInterfaceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FUNCINTERFACEIMPLSERVICE_QNAME, features);
    }

    public FuncInterfaceImplService(URL wsdlLocation) {
        super(wsdlLocation, FUNCINTERFACEIMPLSERVICE_QNAME);
    }

    public FuncInterfaceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FUNCINTERFACEIMPLSERVICE_QNAME, features);
    }

    public FuncInterfaceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FuncInterfaceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FuncInterfaceImpl
     */
    @WebEndpoint(name = "FuncInterfaceImplPort")
    public FuncInterfaceImpl getFuncInterfaceImplPort() {
        return super.getPort(new QName("http://interfaces.webservice.com/", "FuncInterfaceImplPort"), FuncInterfaceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FuncInterfaceImpl
     */
    @WebEndpoint(name = "FuncInterfaceImplPort")
    public FuncInterfaceImpl getFuncInterfaceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://interfaces.webservice.com/", "FuncInterfaceImplPort"), FuncInterfaceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUNCINTERFACEIMPLSERVICE_EXCEPTION!= null) {
            throw FUNCINTERFACEIMPLSERVICE_EXCEPTION;
        }
        return FUNCINTERFACEIMPLSERVICE_WSDL_LOCATION;
    }

}
