
package com.webservice.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FuncInterfaceImpl", targetNamespace = "http://interfaces.webservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FuncInterfaceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saySomething", targetNamespace = "http://interfaces.webservice.com/", className = "com.webservice.server.SaySomething")
    @ResponseWrapper(localName = "saySomethingResponse", targetNamespace = "http://interfaces.webservice.com/", className = "com.webservice.server.SaySomethingResponse")
    @Action(input = "http://interfaces.webservice.com/FuncInterfaceImpl/saySomethingRequest", output = "http://interfaces.webservice.com/FuncInterfaceImpl/saySomethingResponse")
    public String saySomething(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
